### PR TITLE
HMVC Support

### PR DESCRIPTION
**Pull request by daycry**
This file is OK

### CODE REVIEW

**Comment by kenjis** [comment]
Why don't you just add paths for modules in config?
Do you  really need to the functionality which adds module path dynamically?

**Comment by kenjis** [comment]
You can set module path dynamically when loading this Twig library.
See https://github.com/kenjis/codeigniter-ss-twig#loading-twig-library

I don't want to couple this libary with HMVC. Because it is a simple library.

**Comment by daycry** [comment]
I think that is better, because you dont need create any config file.

**Comment by kenjis** [comment]
@daycry I don't use HMVC as possible. Because it provides more complexity to CodeIgniter.
The official CodeIgniter will never support HMVC.
So I don't want to couple my Twig library _tightly_ with HMVC.

At least, you need to write test code for your code.
The current code coverage is 98.51%, but your PR has no test code, and the coverage is 81.61%.

**Pull request closed without merging**
